package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"cubawheeler.io/pkg/cubawheeler"
	"cubawheeler.io/pkg/graph/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginRequest) (*cubawheeler.Token, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, otp string) (*cubawheeler.Token, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Otp is the resolver for the otp field.
func (r *mutationResolver) Otp(ctx context.Context, email string) (string, error) {
	panic(fmt.Errorf("not implemented: Otp - otp"))
}

// RequestTrip is the resolver for the requestTrip field.
func (r *mutationResolver) RequestTrip(ctx context.Context, pickUp float64, dropOff float64) (*cubawheeler.Trip, error) {
	panic(fmt.Errorf("not implemented: RequestTrip - requestTrip"))
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, profile model.UpdateProfile) (*cubawheeler.Profile, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// UpdateTrip is the resolver for the updateTrip field.
func (r *mutationResolver) UpdateTrip(ctx context.Context, update *model.UpdateTrip) (*cubawheeler.Trip, error) {
	panic(fmt.Errorf("not implemented: UpdateTrip - updateTrip"))
}

// AddFavoritePlace is the resolver for the addFavoritePlace field.
func (r *mutationResolver) AddFavoritePlace(ctx context.Context, name string, lat float64, long float64) (*cubawheeler.Location, error) {
	panic(fmt.Errorf("not implemented: AddFavoritePlace - addFavoritePlace"))
}

// FavoritePlaces is the resolver for the favoritePlaces field.
func (r *mutationResolver) FavoritePlaces(ctx context.Context) ([]*cubawheeler.Location, error) {
	panic(fmt.Errorf("not implemented: FavoritePlaces - favoritePlaces"))
}

// AddFavoriteVehicle is the resolver for the addFavoriteVehicle field.
func (r *mutationResolver) AddFavoriteVehicle(ctx context.Context, plate *string) (*cubawheeler.Vehicle, error) {
	panic(fmt.Errorf("not implemented: AddFavoriteVehicle - addFavoriteVehicle"))
}

// FavoriteVehicles is the resolver for the favoriteVehicles field.
func (r *mutationResolver) FavoriteVehicles(ctx context.Context) ([]*cubawheeler.Vehicle, error) {
	panic(fmt.Errorf("not implemented: FavoriteVehicles - favoriteVehicles"))
}

// Dob is the resolver for the dob field.
func (r *profileResolver) Dob(ctx context.Context, obj *cubawheeler.Profile) (*string, error) {
	panic(fmt.Errorf("not implemented: Dob - dob"))
}

// User is the resolver for the user field.
func (r *profileResolver) User(ctx context.Context, obj *cubawheeler.Profile) (*cubawheeler.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filter *model.UserFilter) ([]*cubawheeler.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Trips is the resolver for the trips field.
func (r *queryResolver) Trips(ctx context.Context, user *string) ([]*cubawheeler.Trip, error) {
	panic(fmt.Errorf("not implemented: Trips - trips"))
}

// Charges is the resolver for the charges field.
func (r *queryResolver) Charges(ctx context.Context, user *string) ([]*cubawheeler.Charge, error) {
	panic(fmt.Errorf("not implemented: Charges - charges"))
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, user *string) (*cubawheeler.Profile, error) {
	panic(fmt.Errorf("not implemented: Profile - profile"))
}

// LastNAddress is the resolver for the lastNAddress field.
func (r *queryResolver) LastNAddress(ctx context.Context, number int) ([]*string, error) {
	panic(fmt.Errorf("not implemented: LastNAddress - lastNAddress"))
}

// ExpiryAt is the resolver for the expiry_at field.
func (r *tokenResolver) ExpiryAt(ctx context.Context, obj *cubawheeler.Token) (int, error) {
	panic(fmt.Errorf("not implemented: ExpiryAt - expiry_at"))
}

// StatusHistory is the resolver for the status_history field.
func (r *tripResolver) StatusHistory(ctx context.Context, obj *cubawheeler.Trip) ([]*model.TripStatusHistory, error) {
	panic(fmt.Errorf("not implemented: StatusHistory - status_history"))
}

// Password is the resolver for the password field.
func (r *userResolver) Password(ctx context.Context, obj *cubawheeler.User) (*string, error) {
	panic(fmt.Errorf("not implemented: Password - password"))
}

// ActiveVehicle is the resolver for the active_vehicle field.
func (r *userResolver) ActiveVehicle(ctx context.Context, obj *cubawheeler.User) (*cubawheeler.Vehicle, error) {
	panic(fmt.Errorf("not implemented: ActiveVehicle - active_vehicle"))
}

// Reviews is the resolver for the reviews field.
func (r *userResolver) Reviews(ctx context.Context, obj *cubawheeler.User) ([]*cubawheeler.Review, error) {
	panic(fmt.Errorf("not implemented: Reviews - reviews"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Token returns TokenResolver implementation.
func (r *Resolver) Token() TokenResolver { return &tokenResolver{r} }

// Trip returns TripResolver implementation.
func (r *Resolver) Trip() TripResolver { return &tripResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type profileResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type tokenResolver struct{ *Resolver }
type tripResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
