# fly.toml app configuration file generated for cuba-wheeler on 2023-11-30T05:12:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cuba-wheeler"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]
[build.args]
BP_GO_TARGETS = "./cmd/cubawheeler"

[env]
DB_NAME = "ridecuba"
FLY_PROCESS_GROUP = "app"
PORT = "8080"
PRIMARY_REGION = "waw"
REDIS_ADDR = "redis://default:a4085b0b71394fa8bc1d9a57f52693fe@fly-cuba-wheeler-redis.upstash.io:6379"
SERVER_PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[services]]
protocol = "tcp"
internal_port = 8080

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
