// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Specify the type of the vehicle.
type Balance struct {
	// Map that contain currency and amount for each currency
	Amount int `json:"amount"`
	// Currency
	Currency string `json:"currency"`
}

type Error struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

type Response struct {
	Success bool     `json:"success"`
	Message *string  `json:"message,omitempty"`
	Errors  []*Error `json:"errors,omitempty"`
}

type Transfer struct {
	ID        string `json:"id"`
	From      string `json:"from"`
	To        string `json:"to"`
	Amount    int    `json:"amount"`
	Currency  string `json:"currency"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Wallet struct {
	// Wallet ID
	ID string `json:"id"`
	// Wallet balance
	Balance []*Balance `json:"balance,omitempty"`
	// Wallet prefered currency
	PreferedCurrency string `json:"preferedCurrency"`
}
