apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
            containers:
            - name: gateway.io
              image: rssolutions.registry.jetbrains.space/p/cuba-wheeler/cubawheeler/gateway.io:v1.0.0
              ports:
              - containerPort: 80
              env:
              - name: SUBGRAPHS
                value: "[{ \"name\": \"models\", \"url\": \"http://models:5000/query\" },{ \"name\": \"wallet\", \"url\": \"http://wallet:5002/query\" },{ \"name\": \"orders\", \"url\": \"http://order:5001/query\"}]"
              resources:
                limits:
                  cpu: "0.5"
                  memory: "512Mi"
                requests:
                  cpu: "0.1"
                  memory: "256Mi"
            imagePullSecrets:
              - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer