apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
            containers:
            - name: order
              image: rssolutions.registry.jetbrains.space/p/cuba-wheeler/cubawheeler/order:v1.0.3
              ports:
              - containerPort: 80
              env:
              - name: JWT_SECRET_KEY
                value: "asdasdasdasdasdasdasdasd"
              - name: SMTP_SERVER
                value: "smtp.gmail.com"
              - name: SMTP_PORT
                value: "587"
              - name: SMTP_USER
                value: "rtoledofernandez@gmail.com"
              - name: SMTP_PASS
                value: "chej eqte xkvn yply"
              - name: MONGO_HOST
                value: "mongodb-service"
              - name: MONGO_PORT
                value: "27017"
              - name: MONGO_DB_NAME
                value: "order"
              - name: MONGO_USER
                value: ""
              - name: MONGO_PASS
                value: ""
              - name: APP_NAME
                value: "Order service"
              - name: REDIS_DB
                value: "1"
              - name: SERVER_PORT
                value: "80"
              - name: REDIS_ADDR
                value: "redis://redis:6379"
              - name: SEED
                value: "true"
              - name: WALLET_API
                value: "http://wallet:8004"
              resources:
                limits:
                  cpu: "0.5"
                  memory: "512Mi"
                requests:
                  cpu: "0.1"
                  memory: "256Mi"
            imagePullSecrets:
              - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80
  type: LoadBalancer