apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: rssolutions.registry.jetbrains.space/p/cuba-wheeler/cubawheeler/auth:v1.1
        ports:
        - containerPort: 80
        env:
        - name: JWT_SECRET_KEY
          value: "asdasdasdasdasdasdasdasd"
        - name: SMTP_SERVER
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: "rtoledofernandez@gmail.com"
        - name: SMTP_PASS
          value: "chej eqte xkvn yply"
        - name: MONGO_URL
          value: "mongodb://mongodb-svc:27017/?retryWrites=true&w=majority"
        - name: MONGO_DB_NAME
          value: "auth"
        - name: APP_NAME
          value: "Order service"
        - name: REDIS_DB
          value: "1"
        - name: SERVER_PORT
          value: "80"
        - name: REDIS_ADDR
          value: "redis://redis:6379"
        - name: SEED
          value: "true"
        - name: WALLET_API
          value: "http://wallet:8004"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
  type: LoadBalancer