apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: rssolutions.registry.jetbrains.space/p/cuba-wheeler/cubawheeler/order:v1.1.8
        ports:
        - containerPort: 80
        env:
        - name: AUTH_SERVICE_URL
          value: "http://auth"
        - name: JWT_SECRET_KEY
          value: "asdasdasdasdasdasdasdasd"
        - name: ABLY_API_KEY
          value: "z8TS2w.nyBXtw:7QTI5Uq-wOaCLoazlWNigoh9LEbGIaNdIx4nRb2ZWKM"
        - name: ABLY_API_SUBSCRIBER_KEY
          value: "z8TS2w.nHdvAA:-VDt5rWDKbechfJ6PjkiWeYkAGAs5oeVGuQVJrmQv4Q"
        - name: SMTP_SERVER
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          value: "rtoledofernandez@gmail.com"
        - name: SMTP_PASS
          value: "chej eqte xkvn yply"
        - name: SERVER_PORT
          value: "80"
        - name: MONGO_URL
          value: "mongodb://mongodb-svc:27017/?retryWrites=true&w=majority"
        - name: REDIS_ADDR
          value: "redis://redis:6379"
        - name: MONGO_DB_NAME
          value: "orders"
        - name: APP_NAME
          value: "Order service"
        - name: SEED
          value: "true"
        - name: MAPBOX_TOKEN
          value: "sk.eyJ1IjoiY3ViYXdoZWVsZXJhcHAiLCJhIjoiY2xyNzI3cHNkMDhzejJxbnhvOTljMnd1eCJ9.GYr_A_3ylsdmf2XTtqXQjw"
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 80
  type: LoadBalancer