# redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: redis
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      api: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        api: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP